### ISSUE TITLE
Runtime for AWS EC2

### ISSUE THREAD

**Issue by sergii-mamedov** [lithops-cloud/lithops#1101]
Unfortunately, there is no example Dockerfile for AWS EC2 in the [runtime directory](https://github.com/lithops-cloud/lithops/tree/2.7.0/runtime). There is also a link to the AWS EC2 runtime on the [configuration description page](https://github.com/lithops-cloud/lithops/blob/2.7.0/docs/source/compute_config/aws_ec2.md), which also leads to a non-existent page.

I would appreciate an example Dockerfile for AWS EC2.

**Comment by JosepSampe** [comment]
@sergii-mamedov WIll update the docs. 

However, note that you can use any docker conatiner that contains all your required libraries, since lithops overwrites the default docker entrypoint, so it doesn´t matter wich docker container you use if it is based on Debian/Ubuntu. For example, you can use an IBM Cloud Functions container if you want.

Also note that, for better cold start times, the recomended approach is to use the VM itself as the runtime, without a docker container. For example, you can create a VM in you AWS region, access the VM, install all the dependencies in the VM itself (`apt-get`, `pip3 install`, ...), stop the VM, create a VM Image, and then put the image_id in your lithops config file:

```yaml
aws_ec2:
    ...
    target_ami: <TARGET_AMI>
    ...
```

In this second case, Lithops will use the default `python3` interpreter of the VM

**Comment by RichardScottOZ** [comment]
In this case install the setup into the default python3 as is? In some cases need conda environments...then you would need to handle a different way or use a container?
