### ISSUE TITLE
Different behavior between serverless and localhost FunctionExecutor. 

### ISSUE THREAD

**Issue by gfinol** [lithops-cloud/lithops#1174]
I've seen that `FunctionExecutor` in localhost does not run multiple `map` concurrently, but in the serverless mode it does. 

In my opinion, the expected behavior for the localhost mode would be to run all the jobs concurrently or in batches of the configured max number of workers. 

Here is a code to reproduce it:

```python
import time

import lithops

def my_fn(x):
    time.sleep(5)
    return x + 7

if __name__ == "__main__":
    fexec = lithops.FunctionExecutor(backend='aws_lambda', storage='aws_s3', log_level='DEBUG')
    # fexec = lithops.FunctionExecutor(backend='localhost', storage='localhost', log_level='DEBUG')
    
    fexec.map(my_fn, range(10))
    fexec.map(my_fn, range(10,20))

    res = fexec.get_result()
    fexec.plot()
    print(res)
```

In localhost, it runs the 10 first map jobs, waits for them to finish and runs the remaining 10 map jobs from 2 second `map`.
In serverless, all the 20 functions are invoked at the same time and run concurrently.

**Comment by JosepSampe** [comment]
@gfinol, you are correct that the current approach is not ideal for maximizing resource usage.

I have created a new version of the localhost executor in #1180. For now, I'm keeping both v1 and this new v2 because the entire standalone system depends on v1. This means significant changes are needed to make everything v2 compatible.

If you'd like to give it a try, you can activate v2 in the configuration with:
```yaml
localhost:
    version: 2
```

**Comment by gfinol** [comment]
Thank you, @JosepSampe !
I'll test it asap.
