### ISSUE TITLE
Different behaviours for list_keys depending on the storage backend

### ISSUE THREAD

**Issue by abourramouss** [lithops-cloud/lithops#1194]
Hello,

I have developed a version of a pipeline using k8s and minio.

Then, while porting the same pipeline to aws lambda and s3, i have noticed that the storage api returns different keys for list_keys,

This is the function i am using for both storage backends:

```
def run(self, func_limit: int):
        extra_env = {"HOME": "/tmp"}
        function_executor = lithops.FunctionExecutor()

        print(f"input_data_path.bucket: {self.input_data_path.bucket}")
        print(f"input_data_path.key: {self.input_data_path.key}")
        keys = lithops.Storage().list_keys(
            bucket=self.input_data_path.bucket,
            prefix=f"{self.input_data_path.key}/",
        )
        print(f"keys: {keys}")
...
```

and the output for k8s + minio:

```
input_data_path.bucket: ayman-extract
input_data_path.key: partitions/partitions_10zip
2023-11-10 10:33:26,221 [INFO] lithops.storage.backends.minio.minio - MinIO client created - Endpoint: http://192.168.5.24:9000
keys_size: 10
keys: ['partitions/partitions_10zip/partition_1.ms.zip', 'partitions/partitions_10zip/partition_10.ms.zip', 'partitions/partitions_10zip/partition_2.ms.zip', 'partitions/partitions_10zip/partition_3.ms.zip', 'partitions/partitions_10zip/partition_4.ms.zip', 'partitions/partitions_10zip/partition_5.ms.zip', 'partitions/partitions_10zip/partition_6.ms.zip', 'partitions/partitions_10zip/partition_7.ms.zip', 'partitions/partitions_10zip/partition_8.ms.zip', 'partitions/partitions_10zip/partition_9.ms.zip']

```
output for aws lambda + s3

```
input_data_path.bucket: ayman-extract
input_data_path.key: partitions/partitions_10zip
2023-11-10 11:33:24,050 [INFO] lithops.storage.backends.aws_s3.aws_s3 - S3 client created - Region: us-east-1
keys_size: 11
keys: ['partitions/partitions_10zip/', 'partitions/partitions_10zip/partition_1.ms.zip', 'partitions/partitions_10zip/partition_10.ms.zip', 'partitions/partitions_10zip/partition_2.ms.zip', 'partitions/partitions_10zip/partition_3.ms.zip', 'partitions/partitions_10zip/partition_4.ms.zip', 'partitions/partitions_10zip/partition_5.ms.zip', 'partitions/partitions_10zip/partition_6.ms.zip', 'partitions/partitions_10zip/partition_7.ms.zip', 'partitions/partitions_10zip/partition_8.ms.zip', 'partitions/partitions_10zip/partition_9.ms.zip']
```

as you can see, the returned elements are different, one version adds an extra element to the list which is the root path.

I am using lithops 2.9.0

**Comment by JosepSampe** [comment]
hi @abourramouss , thanks for raising this up, just note that:

1. For some reason, some object stores create "virtual folders" as objects automatically.
2. Some people/apps create these kind of objects manually just to represent a virtual hierarchy in the objects store.
3. In Lithops, both backends have exactly the same logic to list objects and key. 
4. Lithops is intended to lit everything it finds, so if the object is there, it must list it.

That said, I think this is not a Lithops issue. Lithops must list everything it finds and I think it is not a good idea to filter these kind of objects, because some people might be interested on them. So i think you should filter them in your app side if you are not interested on them.

**Comment by abourramouss** [comment]
> hi @abourramouss , thanks for raising this up, just note that:
> 
> 1. For some reason, some object stores create "virtual folders" as objects automatically.
> 2. Some people/apps create these kind of objects manually just to represent a virtual hierarchy in the objects store.
> 3. In Lithops, both backends have exactly the same logic to list objects and key.
> 4. Lithops is intended to lit everything it finds, so if the object is there, it must list it.
> 
> That said, I think this is not a Lithops issue. Lithops must list everything it finds and I think it is not a good idea to filter these kind of objects, because some people might be interested on them. So i think you should filter them in your app side if you are not interested on them.

Thanks for the answer.

What if we did the same for the minio implementation then? just to mantain some uniformity across what methods return, since at first i was getting confused.

**Comment by JosepSampe** [comment]
> What if we did the same for the minio implementation then? just to mantain some uniformity across what methods return, since at first i was getting confused.

This is not a question of doing the same in Minio. Lithops always lists all the objects in the bucket. So if you see this object, it is because in S3 the object is there, and if you don't see it in MinIO, it is because the object is not there. You should check how you create these objects in the backend, and meybe remove all them and start from scratch so see if the object is created again in s3

**Comment by abourramouss** [comment]
> > What if we did the same for the minio implementation then? just to maintain some uniformity across what methods return, since at first i was getting confused.
> 
> This is not a question of doing the same in Minio. Lithops always lists all the objects in the bucket. So if you see this object, it is because in S3 the object is there, and if you don't see it in MinIO, it is because the object is not there. You should check how you create these objects in the backend, and maybe remove all them and start from scratch to see if this object is created again in s3

Well, in aws it just adds the root of the directory to the list (partitions/partitions_10zip/), while in minio doesn't, in the aws as you can see in the picture attached, there isn't the folder that s3 is adding to the list keys.

![image](https://github.com/lithops-cloud/lithops/assets/14056306/9e2da4e4-9966-4198-b5c4-27a741a0bed9)

**Comment by JosepSampe** [comment]
Well, I understand you don't see it in the S3 UI because you are inside it, right? If you go back one step you will see the object in the UI.

As you can see in the image, In the S3 UI you have the option "create folder", this option creates these folder objects. 
So depending on the way you upload the data, it automatically creates these s3 folders.

**Comment by abourramouss** [comment]
> Well, I understand you don't see it in the S3 UI because you are inside it, right? If you go back one step you will see the object in the UI.
> 
> As you can see in the image, In the S3 UI you have the option "create folder", this option creates these folder objects. So depending on the way you upload the data, it automatically creates these s3 folders.

Yes, but in minio, for the same thing (folder and then zips uploaded), i don't get the extra folder when i list the keys ('partitions/partitions_10zip/')

**Comment by JosepSampe** [comment]
This is because they are different services and they work in a different way. How did you upload the data? through the UI in both cases? If you delete everything and you use for example the lithops client, these folder object won't be created
```python
lithops.Storage(backend='aws_s3').upload_file(file_name, bucket, 'dso/test/example/map.py')
```

**Comment by abourramouss** [comment]
Interesting, then i guess i should control the creation of the extra folder from my code and remove it if it's there. Thanks for your fast responses, i really appreciate it!
