### ISSUE TITLE
VM setup without root privileges.

### ISSUE THREAD

**Issue by Daniel8675** [lithops-cloud/lithops#1225]
* Is it possible to run Lithops on a virtual machine where we don't have root privileges? 
* Does the script ```install_lithops.sh``` modify files in the ```/etc``` folder that, without the mentioned privileges, are untouchable?
* Are there plans to work on support for more secure algorithms than RSA for virtual machines?

**Comment by JosepSampe** [comment]
Hi @Daniel8675

>Is it possible to run Lithops on a virtual machine where we don't have root privileges? Does the script install_lithops.sh modify files in the /etc folder that, without the mentioned privileges, are untouchable?

Currently lithops uses `sudo apt` to install all the required packages by lithops, and `sudo systemctl start/stop`, since lithops is installed in the VM as a unix service.

>Are there plans to work on support for more secure algorithms than RSA for virtual machines?

Due to an issue with the [paramiko](https://github.com/paramiko/paramiko) library, we had to force the ssh client to always load RSA keys. So currently there is no plan to adopt another algorithm.
