### ISSUE TITLE
Dynamic workers number for Kvative

### ISSUE THREAD

**Issue by omerb01** [lithops-cloud/lithops#268]
a feature suggestion for the new Knative backhand:
now, workers number is statically defined by default for 1200 workers, this definition is done for CF and Knative as well.

for a default CF account, only 1200 actions are permitted in parallel so defining 1200 workers while using CF is great but while using Knative we depend on the VM (or the local machine) specs.
for example, if we operate a map function including 1200 workers of 2GB while having only 16GB total RAM in my VM using Kubernetes - we will obviously get a memory crash.

Instead of calculating each time the expected workers number for each map operation, I suggest calculating it internally by recognizing Knative usage, getting the total RAM available and dividing it by the requested memory to get the expected workers number.

what do you think?

**Comment by kpavel** [comment]
Sounds good, but it can be slightly more flexible.
Calculating number of available resources before running the job is risky, as it can be changed by concurrently running job.
Maybe you should also consider to recognize failures, when invocation fails because of resource limits and retry, while dynamically managing the number of concurrent workers.

**Comment by gilv** [comment]
@JosepSampe can you check this please?

**Comment by JosepSampe** [comment]
@omerb01 It sounds great. Although in knative the default number of workers is 100 (not 1200), it is much more flexible to calculate it in runtime. However, I have some questions: 
- Should we assume that a given knative cluster/vm is used  only by 1 user? 
- What happens if there are multiple users in the same cluster?

In this case calculating the number of workers will be much more complex, as @kpavel suggested. What if 2 users invoke a job at the same time? both will get the same available resources, but then both jobs will fail because they will be fighting for same resources, right?

**Comment by omerb01** [comment]
@JosepSampe it's a good point. I'm not a Kubernetes expert, but it seems that a cluster over Knative can manage its available resources by external demands, its pods are created by demands and destroyed right after usage, maybe we can calculate available resources regarding current running containers.

**Comment by gilv** [comment]
@omerb01 @JosepSampe adding my 2 cents. I guess it the cluster is dedicated, then this can work..but otherwise @JosepSampe is correct. Even if we see cluster is empty and we calculate X resources based on the current running containers, it still doesn't prevent other from use the same cluster. So we calculate X resources, submit PyWren job and then someone in the middle submitted massive workflow, so our X resources are not available anymore.

**Comment by kpavel** [comment]
I think better solution would be to combine two approaches. 
1. Have hard limit of maximum resources that can be allocated by the cluster.
2. Catch appropriate exceptions, e.g. "overloaded" (error code 503). Then decrease number of workers and consumed resources dynamically and retry failed invocations

**Comment by JosepSampe** [comment]
Closing this for now as we prioritize IBM Code Engine platform, which already does all of this for us.
