### ISSUE TITLE
Ibm_cf| Mandatory Lithops.clean() between changes to functions run in cloud

### ISSUE THREAD

**Issue by Cohen-J-Omer** [lithops-cloud/lithops#628]
Hey @JosepSampe, hope you're doing well :) 
Working on my last objective, I've been using ibm_cf as my computational backend quite a lot.
I've noticed that if i ran a test function, using the Lithops map/map_reduce and then made any changes to the test function or to a few of the projects' files, said changes wouldn't take effect, even if i ran FunctionExecutor's clean() (with any and all parameters).   
Only by running "lithops clean" in the terminal, thus cleaning the backed-up runtime, the updated files would run by ibm_cf on the next run. 

So, I wonder: 
1. Is FunctionExecutor's clean() working as intended? 
2. Is there a more user friendly approach to update files in the cloud, so that ibm_cf would notice said changes (other than running "lithops clean" in the terminal between each update). 

I'll greatly appreciate your help in the matter.

**Comment by JosepSampe** [comment]
Hey @Cohen-J-Omer, hope you are doing well too ;)

Just note that `FunctionExecutor.clean()` is one thing, and `lithops clean` is another diferent thing.
- FunctionExecutor.clean() is used to clean the temp data generated in the jobs you ran with that executor.
- `lithops clean` is used to clean absolutely everything related to lithops (temp data,  local cache, runtimes,...) and start from scratch, as if you just installed lithops.

The changes are automatically deployed when you change the version number [here](https://github.com/lithops-cloud/lithops/blob/master/lithops/version.py). So common users that are not doing development, but just using lithops as any other library, runtimes are automatically updated each time we release a new version, so no problem here.

For those who are doing development, as you said, each time we want to test the changes we need to update the runtime. The correct way to do this would be with `lithops runtime update <RUNTIME_NAME>` command and not with `lithops clean`. [Read this](https://github.com/lithops-cloud/lithops/blob/master/DEVELOPMENT.md#runtime).
`lithops clean` command is the "hard way" to update a runtime, since it deletes everything, so the next time you run a script lithops is forced to create the runtime again (with the new code).

**Comment by Cohen-J-Omer** [comment]
Thanks for the detailed reply! 
I've ran a test to try your suggestions and gathered the following findings, which I would like to check with you:
- Apparently (perhaps due to the recent update to 2.3.1.dev3) changes to the map function itself are triggering an update, regardless of whether the version is 2.3.0 or 2.3.1.dev3.
- Changing to 2.3.0 doesn't trigger an update when making changes to the lithops project files (such as adding a print command to taskrunner.py). 
- When running version 2.3.1.dev3, changes aren't taking effect when issuing either "lithops runtime update default" or "lithops runtime update all" from the runtime folder.

**Comment by JosepSampe** [comment]
@Cohen-J-Omer hmm.. not exactly. 
Basically, independently of the version you use, local changes are deployed when:
- After issuing `lithops runtime update ....` or `lithops clean`
- After changing lithops version.

**Comment by Cohen-J-Omer** [comment]
Thanks, great to know, although it doesn't coincide with my first point and doesn't apply to the issue raised at the last point, i.e.: 
1. Changes to the map function itself are still triggering an update. 
2. Running "lithops runtime update ..." doesn't trigger an update.

**Comment by JosepSampe** [comment]
1. "_Changes to the map function itself are still triggering an update._" 
To what changes do you refer? lithops lib code? or the function code you pass to the map call?


2. "_Running "lithops runtime update ..." doesn't trigger an update._" 
In this case the command  "lithops runtime update ..." is the update trigger, so, yes, it does not trigger an updated since the update is already performed.

**Comment by JosepSampe** [comment]
1. Changes to the map function do not trigger an update. The function in IBM CF only contains the lithops core lib. The map function that a user provides is always stored in COS. So the function itself is never updated.

2. Ok, need to test. We all always use "lithops clean", so it might be posible that "lithops runtime update ..." has an issue.

**Comment by JosepSampe** [comment]
In Lithops, user functions are note deployed in IBM CF. In lithops, the IBM CF function only contains the lithops core code (this repo). You can see the lithops IBM CF function as a wrapper of the actual user function. Then, each time you submit a map(), the user function is serialized in COS, and then, when the lithops IBM CF function receives an invocation, it goes to COS, gets the user function, and executes it.

**Comment by JosepSampe** [comment]
Great! for any other question contact me through email (josep.sampe@urv.cat), no need to open an issue ;)

**Comment by JosepSampe** [comment]
I tested `lithops runtime update ...` and it works properly
