### ISSUE TITLE
Lithops config documentations

### ISSUE THREAD

**Issue by Cohen-J-Omer** [lithops-cloud/lithops#816]
Hey @JosepSampe, 
I believe we should reprioritize the config options that appear on the lithops config documentations, so that the config option that is based on iam api key would be placed first, while a message or a title would precede the other options, stating that they mainly for backwards computability. 
For example the HMAC option in cos is discouraged. Same goes for creating a cloud foundry based namespace.
     
What do you think?

**Comment by JosepSampe** [comment]
@Cohen-J-Omer Are you talking about IBM backends? 

IMO, HMAC credentials and cloudfoundry apikeys are pretty useful; 

IBM IAM generates a token that lasts for 30 minutes. In Lithop it is a problem if a token expires during the execution of a function, since then everything will fail. IMO, IAM is ok for little applications that lasts for only few minutes.

HMAC credentials and cloud foundry api keys never expire. So with them you can execute long-running workflows or big applications without worrying about token expiry time. In fact we have multiple applications that had to switch from IAM to HMAC/CF-Apikey for this reason, for example: https://github.com/metaspace2020/Lithops-METASPACE, https://github.com/faas-prototypes/protomol, https://github.com/triggerflow,

**Comment by Cohen-J-Omer** [comment]
@erezh16 , @kpavel We need to close this issue. 
Do you think it be more conducive for most of lithops' users, or at the very least newcomers, to be introduced to IamApiKey based configurations, before the other configuration options? Meaning, should we shift the position of IamApiKey based configurations to the top of the documentations?
