### ISSUE TITLE
Memory stats

### ISSUE THREAD

**Issue by tomwhite** [lithops-cloud/lithops#970]
It would be useful to include memory usage stats in the `ResponseFuture` `stats` dictionary.

I've found it useful to record the peak memory usage before and after the function invocation in my application:

https://github.com/tomwhite/cubed/blob/50ac4c874ca8f1b1f2a525988252989d8fb2b682/cubed/runtime/executors/lithops.py#L185-L187

where peak memory is measured as follows:

https://github.com/tomwhite/cubed/blob/50ac4c874ca8f1b1f2a525988252989d8fb2b682/cubed/utils.py#L68-L73

Is this something that would be considered for inclusion in lithops?

**Comment by JosepSampe** [comment]
Currently in Lithops we have this utility function https://github.com/lithops-cloud/lithops/blob/master/lithops/worker/utils.py#L113-L134 that measures the memory usage (using psmem module) of the lithops process a the time it is called.

We can include something similar to what you have in stats, yes. 

Just one question about your code: when a runtime receives multiple invocations, one after another, what is the output of `ru_maxrss` in the 2nd function? I mean, if the first functions has a peak of 1GB and the 2nd function has a peak of 0.5GB, will the 2nd function return 1GB because they ran in the same runtime instance, and the max was 1GB? If so, can be `ru_maxrss` rested at the beginning of the function execution?

**Comment by tomwhite** [comment]
Thanks @JosepSampe!

>  if the first functions has a peak of 1GB and the 2nd function has a peak of 0.5GB, will the 2nd function return 1GB because they ran in the same runtime instance, and the max was 1GB?

Yes that's what will happen. This is still useful though, since what I want to know is what the peak memory usage is in practice, so I can see how close it is to the serverless container limit.

Perhaps the best thing to do is provide both peak memory and current memory usage (before and after invocation of the function) - that is, return four stats?

**Comment by JosepSampe** [comment]
@tomwhite Added on master branch

**Comment by tomwhite** [comment]
Great, thanks @JosepSampe! I'm on vacation this week but will try it out when I get back.

**Comment by tomwhite** [comment]
I just tried this out but it's not giving the right memory usage numbers. After a bit of digging, it looks like the memory usage is measured in the process that launches the `JobRunner` process, and not the `JobRunner` process itself:

https://github.com/lithops-cloud/lithops/blob/5bd9bc5614625aa27bdfebb10ddfbff5bbb264d6/lithops/worker/handler.py#L176-L186

I also found that I needed to add `'end'` to the list of keys to include in stats here:
https://github.com/lithops-cloud/lithops/blob/5bd9bc5614625aa27bdfebb10ddfbff5bbb264d6/lithops/future.py#L265

**Comment by JosepSampe** [comment]
@tomwhite I moved it to jobrunner

**Comment by tomwhite** [comment]
@JosepSampe Great! That works for me now. Thanks again.
